# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import currency_pb2 as currency__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in currency_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CurrencyConverterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.unary_unary(
                '/currency.CurrencyConverter/Convert',
                request_serializer=currency__pb2.ConvertRequest.SerializeToString,
                response_deserializer=currency__pb2.ConvertReply.FromString,
                _registered_method=True)
        self.GetSupportedCurrencies = channel.unary_stream(
                '/currency.CurrencyConverter/GetSupportedCurrencies',
                request_serializer=currency__pb2.Empty.SerializeToString,
                response_deserializer=currency__pb2.Currency.FromString,
                _registered_method=True)
        self.StreamRates = channel.unary_stream(
                '/currency.CurrencyConverter/StreamRates',
                request_serializer=currency__pb2.Empty.SerializeToString,
                response_deserializer=currency__pb2.ConvertReply.FromString,
                _registered_method=True)
        self.GetRate = channel.unary_unary(
                '/currency.CurrencyConverter/GetRate',
                request_serializer=currency__pb2.RateRequest.SerializeToString,
                response_deserializer=currency__pb2.RateReply.FromString,
                _registered_method=True)


class CurrencyConverterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Convert(self, request, context):
        """Conversión simple (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedCurrencies(self, request, context):
        """El servidor envía la lista de monedas soportadas (stream)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRates(self, request, context):
        """(Opcional) El servidor stream de tasas periódicas (simulado)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CurrencyConverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Convert': grpc.unary_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=currency__pb2.ConvertRequest.FromString,
                    response_serializer=currency__pb2.ConvertReply.SerializeToString,
            ),
            'GetSupportedCurrencies': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSupportedCurrencies,
                    request_deserializer=currency__pb2.Empty.FromString,
                    response_serializer=currency__pb2.Currency.SerializeToString,
            ),
            'StreamRates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRates,
                    request_deserializer=currency__pb2.Empty.FromString,
                    response_serializer=currency__pb2.ConvertReply.SerializeToString,
            ),
            'GetRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRate,
                    request_deserializer=currency__pb2.RateRequest.FromString,
                    response_serializer=currency__pb2.RateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'currency.CurrencyConverter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('currency.CurrencyConverter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CurrencyConverter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/currency.CurrencyConverter/Convert',
            currency__pb2.ConvertRequest.SerializeToString,
            currency__pb2.ConvertReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportedCurrencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/currency.CurrencyConverter/GetSupportedCurrencies',
            currency__pb2.Empty.SerializeToString,
            currency__pb2.Currency.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/currency.CurrencyConverter/StreamRates',
            currency__pb2.Empty.SerializeToString,
            currency__pb2.ConvertReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/currency.CurrencyConverter/GetRate',
            currency__pb2.RateRequest.SerializeToString,
            currency__pb2.RateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
