# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/currency.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/currency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/currency.proto\x12\x08\x63urrency\"L\n\x0e\x43onvertRequest\x12\x15\n\rfrom_currency\x18\x01 \x01(\t\x12\x13\n\x0bto_currency\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"b\n\x0c\x43onvertReply\x12\x18\n\x10\x63onverted_amount\x18\x01 \x01(\x01\x12\x0c\n\x04rate\x18\x02 \x01(\x01\x12\x15\n\rfrom_currency\x18\x03 \x01(\t\x12\x13\n\x0bto_currency\x18\x04 \x01(\t\"&\n\x08\x43urrency\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"9\n\x0bRateRequest\x12\x15\n\rfrom_currency\x18\x01 \x01(\t\x12\x13\n\x0bto_currency\x18\x02 \x01(\t\"\x19\n\tRateReply\x12\x0c\n\x04rate\x18\x01 \x01(\x01\x32\x82\x02\n\x11\x43urrencyConverter\x12;\n\x07\x43onvert\x12\x18.currency.ConvertRequest\x1a\x16.currency.ConvertReply\x12\x35\n\x07GetRate\x12\x15.currency.RateRequest\x1a\x13.currency.RateReply\x12?\n\x16GetSupportedCurrencies\x12\x0f.currency.Empty\x1a\x12.currency.Currency0\x01\x12\x38\n\x0bStreamRates\x12\x0f.currency.Empty\x1a\x16.currency.ConvertReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.currency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTREQUEST']._serialized_start=34
  _globals['_CONVERTREQUEST']._serialized_end=110
  _globals['_CONVERTREPLY']._serialized_start=112
  _globals['_CONVERTREPLY']._serialized_end=210
  _globals['_CURRENCY']._serialized_start=212
  _globals['_CURRENCY']._serialized_end=250
  _globals['_EMPTY']._serialized_start=252
  _globals['_EMPTY']._serialized_end=259
  _globals['_RATEREQUEST']._serialized_start=261
  _globals['_RATEREQUEST']._serialized_end=318
  _globals['_RATEREPLY']._serialized_start=320
  _globals['_RATEREPLY']._serialized_end=345
  _globals['_CURRENCYCONVERTER']._serialized_start=348
  _globals['_CURRENCYCONVERTER']._serialized_end=606
# @@protoc_insertion_point(module_scope)
